#!/bin/bash
set -v

./destroy

javac *.java
rmic BlockchainImpl

#On personnalise les noms deq class qu'on enverra à l'autre Noeud_Block
mv BlockchainImpl_Stub.class BlockchainImpl_Stub_NB1.class
mv Blockchain.class Blockchain_NB1.class

#On envoit ce dont mon peer aura besoin à l'autre Noeud_Block
for i in BlockchainImpl_Stub_NB1 Blockchain_NB1
do  cp $i.class ../Noeud_Block2 ../Noeud_Participant1_NB1 ../Noeud_Participant2_NB1 ; done

#On le remmet avec les bons noms pour compatibilité avec les classes existentes
mv BlockchainImpl_Stub_NB1.class BlockchainImpl_Stub.class
mv Blockchain_NB1.class Blockchain.class

#I'll be waiting for 5sec in order to let my peer to launch his server
rmiregistry 2222 &
java Noeud_Block 2222 4242
