#!/bin/bash
set -v

# TOUJOURS ./destroy avant de .build

javac *.java
rmic BlockchainImpl

#On envoit ce dont le Participant3 aura besoin
cp BlockchainImpl_Stub.class ../Noeud_Participant3_NB2

#On personnalise les noms des class qu'on enverra à l'autre Noeud_Block
mv BlockchainImpl_Stub.class BlockchainImpl_Stub_NB2.class

#On envoit ce dont mon peer NB1 aura besoin
cp BlockchainImpl_Stub_NB2.class ../Noeud_Block1

#On le remmet avec les bons noms pour compatibilité avec les classes existentes
mv BlockchainImpl_Stub_NB2.class BlockchainImpl_Stub.class
mv Blockchain_NB2.class Blockchain.class


################################################
################                ################
################################################


#I'll be waiting for 5sec in order to let my peer to launch his server
rmiregistry 4242 &
java -Djava.security.manager -Djava.security.policy=java.policy Noeud_Block 4242 2222
