#!/bin/bash
set -v

\rm *.class



javac *.java
rmic BlockchainImpl

#On personnalise les noms deq class qu'on enverra à l'autre Noeud_Block
mv BlockchainImpl_Stub.class BlockchainImpl_Stub_NB2.class
mv Blockchain.class Blockchain_NB2.class

#On envoit ce dont mon peer aura besoin à l'autre Noeud_Block
for i in BlockchainImpl_Stub_NB2 Blockchain_NB2
do  cp $i.class Noeud_Block1 ; done

#I'll be waiting for 5sec in order to let my peer to launch his server
rmiregistry 4242 & java Noeud_Block1 4242 2222
